### ISSUE TITLE
solrpy can't handle parsing * from response

### ISSUE THREAD

**Issue by johnscancella** [edsu/solrpy#45]
I am making a request using solrpy with the query being `+type:page +date:[18570101 TO 19181231] +ocr_swe:*`. As you can see from the logs below that it is failing to parse the response correctly. The version of solr is 4.10

```
INFO 2018-04-09 13:45:36,727 core 21734 140348382594816 solrpy request: q=%2Btype%3Apage+%2Bdate%3A%5B18570101+TO+19181231%5D+%2Bocr_swe%3A%2A&version=2.2&fl=id%2Cscore&wt=standard
INFO 2018-04-09 13:45:36,730 core 21734 140348382594816 solrpy got response: <?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader"><int name="status">0</int><int name="QTime">1</int><lst name="params"><str name="fl">id,score</str><str name="q">+type:page +date:[18570101 TO 19181231] +ocr_swe:*</str><str name="wt">standard</str><str name="version">2.2</str></lst></lst><result name="response" numFound="3686" start="0" maxScore="1.7325966"><doc><str name="id">/lccn/sn89064413/1858-08-16/ed-1/seq-1/</str><float name="score">1.7325966</float></doc><doc><str name="id">/lccn/sn89064413/1858-08-16/ed-1/seq-2/</str><float name="score">1.7325966</float></doc><doc><str name="id">/lccn/sn89064413/1858-08-16/ed-1/seq-3/</str><float name="score">1.7325966</float></doc><doc><str name="id">/lccn/sn89064413/1858-08-16/ed-1/seq-4/</str><float name="score">1.7325966</float></doc><doc><str name="id">/lccn/sn89064413/1858-08-16/ed-1/seq-5/</str><float name="score">1.7325966</float></doc><doc><str name="id">/lccn/sn89064413/1858-08-16/ed-1/seq-6/</str><float name="score">1.7325966</float></doc><doc><str name="id">/lccn/sn89064413/1858-08-16/ed-1/seq-7/</str><float name="score">1.7325966</float></doc><doc><str name="id">/lccn/sn89064413/1858-08-31/ed-1/seq-1/</str><float name="score">1.7325966</float></doc><doc><str name="id">/lccn/sn89064413/1858-08-31/ed-1/seq-2/</str><float name="score">1.7325966</float></doc><doc><str name="id">/lccn/sn89064413/1858-08-31/ed-1/seq-3/</str><float name="score">1.7325966</float></doc></result>
</response>

INFO 2018-04-09 13:45:36,732 core 21734 140348382594816 solrpy request: hl.requireFieldMatch=true&rows=20&hl.fl=ocr%2Cocr_ara%2Cocr_cze%2Cocr_dak%2Cocr_dan%2Cocr_eng%2Cocr_fin%2Cocr_fre%2Cocr_ger%2Cocr_hrv%2Cocr_ice%2Cocr_ita%2Cocr_lit%2Cocr_nob%2Cocr_pol%2Cocr_rum%2Cocr_slo%2Cocr_slv%2Cocr_spa%2Cocr_swe&version=2.2&hl.snippets=100&q=%2Btype%3Apage+%2Bdate%3A%5B18570101+TO+19181231%5D+%2Bocr_swe%3A%2A&start=0&wt=standard&hl.maxAnalyzedChars=102400&hl=true&debug=True&fl=id%2Ctitle%2Cdate%2Csequence%2Cedition_label%2Csection_label%2Cscore
ERROR 2018-04-09 13:45:36,818 base 21734 140348382594816 Internal Server Error: /search/pages/results/
Traceback (most recent call last):
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/chronam/core/decorator.py", line 96, in new_f
    response = f(*args, **kwargs)
  File "/opt/chronam/core/decorator.py", line 30, in decorated_function
    response = function(*args, **kwargs)
  File "/opt/chronam/core/decorator.py", line 82, in f1
    return f(request, **kwargs)
  File "/opt/chronam/core/views/search.py", line 46, in search_pages_results
    page = paginator.page(paginator._cur_page)
  File "/opt/chronam/core/index.py", line 155, in page
    **params)
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/solr/core.py", line 704, in query
    return self.select(*args, **params)
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/solr/core.py", line 799, in __call__
    xml = self.raw(**params)
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/solr/core.py", line 823, in raw
    rsp = conn._post(self.selector, request, conn.form_headers)
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/solr/core.py", line 640, in _post
    return check_response_status(self.conn.getresponse())
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/solr/core.py", line 1103, in check_response_status
    raise ex
SolrException: HTTP code=500, reason=Server Error
ERROR 2018-04-09 13:45:36,818 base 21734 140348382594816 Internal Server Error: /search/pages/results/
Traceback (most recent call last):
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/chronam/core/decorator.py", line 96, in new_f
    response = f(*args, **kwargs)
  File "/opt/chronam/core/decorator.py", line 30, in decorated_function
    response = function(*args, **kwargs)
  File "/opt/chronam/core/decorator.py", line 82, in f1
    return f(request, **kwargs)
  File "/opt/chronam/core/views/search.py", line 46, in search_pages_results
    page = paginator.page(paginator._cur_page)
  File "/opt/chronam/core/index.py", line 155, in page
    **params)
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/solr/core.py", line 704, in query
    return self.select(*args, **params)
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/solr/core.py", line 799, in __call__
    xml = self.raw(**params)
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/solr/core.py", line 823, in raw
    rsp = conn._post(self.selector, request, conn.form_headers)
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/solr/core.py", line 640, in _post
    return check_response_status(self.conn.getresponse())
  File "/opt/chronam/ENV/local/lib/python2.7/site-packages/solr/core.py", line 1103, in check_response_status
    raise ex
SolrException: HTTP code=500, reason=Server Error
```

**Comment by johnscancella** [comment]
Looks like by adding the `*` I am actually running into the `TooManyClauses` exception. It would be really nice if solr actually reported this correctly instead of just `Server Error`
